name: Java CI

on:
  push:
    branches: [ development, master ]
    paths-ignore:
      - "docs/**"
  pull_request:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3.2.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3.9.0
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Cache Maven packages
        uses: actions/cache@v3.0.11
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run:  xvfb-run mvn package

      - name: Run Sonar analysis
        run: xvfb-run mvn -Dsonar.login=${{ secrets.SONAR_LOGIN }} jacoco:prepare-agent install jacoco:report org.sonarsource.scanner.maven:sonar-maven-plugin:RELEASE:sonar
